services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: groupshot
      POSTGRES_PASSWORD: groupshot
      POSTGRES_DB: groupshot
    ports:
      - 5433:5432
    volumes:
      - ./prisma/postgres-data:/var/lib/postgresql/data
